### ISSUE TITLE
error: could not convert template argument

### ISSUE THREAD

**Issue by lxm1117** [gfrd/egfrd#110]
Got an error message when executing make to install.
System installed on Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux.
Error looks like below. 

----------------------------------------------------
make  all-recursive
make[1]: Entering directory '/home/neuro/Downloads/egfrd/egfrd'
Making all in binding
make[2]: Entering directory '/home/neuro/Downloads/egfrd/egfrd/binding'
depbase=`echo model_class.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..    -DNO_IMPORT -I.. -I/usr/include -I/usr/include -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include -g -O2 -Wall -MT model_class.lo -MD -MP -MF $depbase.Tpo -c -o model_class.lo model_class.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -DNO_IMPORT -I.. -I/usr/include -I/usr/include -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include -g -O2 -Wall -MT model_class.lo -MD -MP -MF .deps/model_class.Tpo -c model_class.cpp  -fPIC -DPIC -o .libs/model_class.o
In file included from ../peer/utils.hpp:4:0,
                 from Model.hpp:6,
                 from model_class.cpp:5:
../peer/util/range_from_range.hpp: In instantiation of 'boost::python::api::object peer::util::range_from_range() [with T1_ = boost::iterator_range<std::tr1::__detail::_Hashtable_const_iterator<std::pair<const std::basic_string<char>, std::basic_string<char> >, false, false> >; T2_ = Model; T1_ (T2_::* Vfun_)() const = &Model::attributes]':
Model.hpp:40:56:   required from 'void binding::register_model_class(const char*) [with Tmodel_ = Model]'
model_class.cpp:12:40:   required from here
../peer/util/range_from_range.hpp:101:68: error: could not convert template argument '&Model::attributes' to 'boost::iterator_range<std::tr1::__detail::_Hashtable_const_iterator<std::pair<const std::basic_string<char>, std::basic_string<char> >, false, false> > (Model::*)()'
     return detail::range_from_range<T1_, const T2_, Vfun_>::create();
                                                                    ^
../peer/util/range_from_range.hpp: In instantiation of 'boost::python::api::object peer::util::range_from_range() [with T1_ = boost::iterator_range<boost::transform_iterator<select_second<std::pair<const SpeciesTypeID, boost::shared_ptr<SpeciesType> > >, std::_Rb_tree_const_iterator<std::pair<const SpeciesTypeID, boost::shared_ptr<SpeciesType> > > > >; T2_ = Model; T1_ (T2_::* Vfun_)() const = &Model::get_species_types]':
Model.hpp:44:63:   required from 'void binding::register_model_class(const char*) [with Tmodel_ = Model]'
model_class.cpp:12:40:   required from here
../peer/util/range_from_range.hpp:101:68: error: could not convert template argument '&Model::get_species_types' to 'boost::iterator_range<boost::transform_iterator<select_second<std::pair<const SpeciesTypeID, boost::shared_ptr<SpeciesType> > >, std::_Rb_tree_const_iterator<std::pair<const SpeciesTypeID, boost::shared_ptr<SpeciesType> > > > > (Model::*)()'
../peer/util/range_from_range.hpp: In function 'boost::python::api::object peer::util::range_from_range() [with T1_ = boost::iterator_range<boost::transform_iterator<select_second<std::pair<const SpeciesTypeID, boost::shared_ptr<SpeciesType> > >, std::_Rb_tree_const_iterator<std::pair<const SpeciesTypeID, boost::shared_ptr<SpeciesType> > > > >; T2_ = Model; T1_ (T2_::* Vfun_)() const = &Model::get_species_types]':
../peer/util/range_from_range.hpp:102:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../peer/util/range_from_range.hpp: In function 'boost::python::api::object peer::util::range_from_range() [with T1_ = boost::iterator_range<std::tr1::__detail::_Hashtable_const_iterator<std::pair<const std::basic_string<char>, std::basic_string<char> >, false, false> >; T2_ = Model; T1_ (T2_::* Vfun_)() const = &Model::attributes]':
../peer/util/range_from_range.hpp:102:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:563: recipe for target 'model_class.lo' failed
make[2]: *** [model_class.lo] Error 1
make[2]: Leaving directory '/home/neuro/Downloads/egfrd/egfrd/binding'
Makefile:1012: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/neuro/Downloads/egfrd/egfrd'
Makefile:683: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Seynen** [comment]
Hello Ximi,
this is a known issue, probably your compiler is too new for this old codebase.
use GCC 4.8 (and not later).
Regards,
seynen

**Comment by Seynen** [comment]
This issue has been resolved, see fix in 
https://github.com/Seynen/egfrd/commit/cb80da167193972b919e2d5a84007d9c9c3f47e5
