### ISSUE TITLE
Issue with "Make" 

### ISSUE THREAD

**Issue by alastair-JL** [gfrd/egfrd#111]
Currently trying to install without much luck- am in Ubuntu 16.10. Have installed all the recommended packages, and switched to GCC 4.8, but whenever I run "Make" I get a bunch of error messages along the lines of 

"in file included from binding_common.hpp:23:0,
                 from bd_propagator_class.cpp:6:
../World.hpp: At global scope:
../World.hpp:48:35: error: ‘constexpr’ needed for in-class initialization of static data member ‘const Real WorldTraitsBase<Tderived_, Tlen_, TD_>::TOLERANCE’ of non-integral type [-fpermissive]
     static const Real TOLERANCE = 1e-7;
                                   ^~~~"

And Make eventually exits with the recipe failed and error type 2.
Not really sure if this is something in the code or in my set up, but figured I'd ask in case it has been seen before... happy to provide log files or anything else if helpful.

**Comment by Seynen** [comment]
Hi alastair-JL, 
you can try my fork at https://github.com/seynen/egfrd which is functionally identical to this, and has the required fixes to build with 'recent' compilers.
Tested on Ubuntu 16.10/GCC6.2

**Comment by alastair-JL** [comment]
Wonderful- compiled beautifully. Thanks heaps.
