### ISSUE TITLE
__debug__ is a "constant" python variable

### ISSUE THREAD

**Issue by Jintram** [gfrd/egfrd#58]
# Never mind this

See below, the comment that starts with "AH! Oops!".

**Problem**

We're using the variable __debug__ to decide whether to perform checks or not in the algorithm.

This is a rather inconvenient choice, as __debug__ is a constant, which only changes if you start python with the -O option. See also http://docs.python.org/library/constants.html.

**Excerpt from mentioned url:**

__debug__

   This constant is true if Python was not started with an -O option. See also the assert statement.

Note

The names None and __debug__ cannot be reassigned (assignments to them, even as an attribute name, raise SyntaxError), so they can be considered “true” constants.

Changed in version 2.7: Assignments to __debug__ as an attribute became illegal.

**Suggested solution**

Change the use of __debug__ to a "custom" constant we set in some file, which is by default set to "False". This way, users can optionally assign the value "False" to the constant. A name for the constant could e.g. be "PERFORM_CHECKS".

**Comment by Jintram** [comment]
I've made two commits that have this feature in my Lau_debugging branch.

The second commit modifies some code that should have been conditional, i.e. dependent on settings.PERFORM_CHECKS. It now is. Note that there might be more code that still needs to become conditional (basically due to typos).

**Comment by thomie** [comment]
> >  inconvenient choice
- with -O: faster simulations
- without -O: easier debugging

**Comment by Jintram** [comment]
AH! Oops!

I run my scripts via the command line, i.e. 

```
$ ./myscript.py
```

In that case you can't _directly_ use -O. But of course, you **can**. 

Using 

```
$ python -O myscript.py
```

Or, but I'd have to check, by defining your first line in the script, say

```
#!/usr/bin/python -O
```

All right, let me close this issue and let's all forget I ever posted this ;-) Thanks for those two lines of wisdom mr. Miedema!
